export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_EMAIL_IS_NOT_VERIFIED = "USER_EMAIL_IS_NOT_VERIFIED";

export const USER_RESEND_EMAIL_REQUEST = "USER_RESEND_EMAIL_REQUEST";
export const USER_RESEND_EMAIL_SUCCESS = "USER_RESEND_EMAIL_SUCCESS";
export const USER_RESEND_EMAIL_FAIL = "USER_RESEND_EMAIL_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";