export const USER_GET_CART_REQUEST = "USER_GET_CART_REQUEST";
export const USER_GET_CART_SUCCESS = "USER_GET_CART_SUCCESS";
export const USER_GET_CART_FAIL = "USER_GET_CART_FAIL";

export const USER_CLEAN_CART = "USER_CLEAN_CART";

export const USER_GET_COUNTRY_OPTION_REQUEST = "USER_GET_COUNTRY_OPTION_REQUEST";
export const USER_GET_COUNTRY_OPTION_SUCCESS = "USER_GET_COUNTRY_OPTION_SUCCESS";
export const USER_GET_COUNTRY_OPTION_FAIL = "USER_GET_COUNTRY_OPTION_FAIL";