export const USER_GET_CURRENT_PLAN_REQUEST = "USER_GET_CURRENT_PLAN_REQUEST";
export const USER_GET_CURRENT_PLAN_SUCCESS = "USER_GET_CURRENT_PLAN_SUCCESS";
export const USER_GET_CURRENT_PLAN_FAIL = "USER_GET_CURRENT_PLAN_FAIL";
export const USER_GET_CURRENT_PLAN_CLEAR_DATA = "USER_GET_CURRENT_PLAN_CLEAR_DATA";

export const USER_GET_ALL_PLAN_REQUEST = "USER_GET_ALL_PLAN_REQUEST";
export const USER_GET_ALL_PLAN_SUCCESS = "USER_GET_ALL_PLAN_SUCCESS";
export const USER_GET_ALL_PLAN_PLAN_FAIL = "USER_GET_ALL_PLAN_PLAN_FAIL";
export const CLEAR_USER_GET_ALL_PLAN_DATA = "CLEAR_USER_GET_ALL_PLAN_DATA";