export const USER_REPORT_OPTION_REQUEST = 'USER_REPORT_OPTION_REQUEST';
export const USER_REPORT_OPTION_SUCCESS_INFO = 'USER_REPORT_OPTION_SUCCESS_INFO';
export const USER_REPORT_OPTION_FAIL = 'USER_REPORT_OPTION_FAIL';