export const ADMIN_PROFILE_INFO_REQUEST = 'ADMIN_PROFILE_INFO_REQUEST';
export const ADMIN_PROFILE_INFO_SUCCESS = 'ADMIN_PROFILE_INFO_SUCCESS'; 
export const ADMIN_PROFILE_INFO_FAIL = 'ADMIN_PROFILE_INFO_FAIL';
export const GET_ADMIN_USER_REQUEST = 'GET_ADMIN_USER_REQUEST';
export const GET_ADMIN_USER_INFO_SUCCESS = 'GET_ADMIN_USER_INFO_SUCCESS';
export const GET_ADMIN_USER_INFO_FAIL = 'GET_ADMIN_USER_INFO_FAIL';